
message-processor:
  default-schedule: "*/5 * * * * *"
  offset-schedule: "02/32 * * * * *"
  working-hours-schedule: "*/5 * * * * *"
  default-min-lock-time: PT4S
  default-max-lock-time: PT1M

payment-cycle:
  schedule:
    cron-schedule: "*/30 * * * * *"
    minimum-lock-time: "PT10S"
    maximum-lock-time: "PT2M"

enable-scheduler: true
