package uk.gov.dhsc.htbhf.claimant.message;

public enum MessageType {
    REQUEST_NEW_CARD,
    COMPLETE_NEW_CARD_PROCESS,
    MAKE_FIRST_PAYMENT,
    MAKE_PAYMENT,
    SEND_EMAIL,
    SEND_LETTER,
    DETERMINE_ENTITLEMENT,
    ADDITIONAL_PREGNANCY_PAYMENT,
    REPORT_CLAIM,
    REPORT_PAYMENT
}
